---
title: "C Project 1"
author: "Kristina Golden"
date: "2023-06-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Required packages
```{r message=FALSE, include=FALSE}
library(httr)
library(jsonlite)
library(tidyverse)
library(TAF)
library(gt)
library(kableExtra)
library(ggplot2)
library(ggalt)
library(expss)
API_KEY <- Sys.setenv("API_KEY" =
                        "_aL5f5EmEje0vL6kYr1xOPtgR8e9rGwT")
```

##Functions

```{r}
#Function for company name
company <- function(company = "all"){
  url <- "https://api.polygon.io/v2/snapshot/locale/us/markets/stocks/tickers"
  query_list <- list(apiKey =
                       Sys.getenv("API_KEY"))
  my_data <- GET(url, query = query_list)
  parsed <- fromJSON(rawToChar(my_data$content))
  options <- as.data.frame(parsed$tickers)
  options <- options %>% unnest('day')
      options <- rename(options, 
                 Day_Open_Price = o, 
                 Day_High_Price = h,
                 Day_Low_Price = l,
                 Day_Close_Price = c,
                 d1 = v,
                 d2 = vw)
      options <- options %>% unnest('prevDay')
      options <- rename(options, 
                  Prev_Open_Price = o, 
                  Prev_High_Price = h,
                  Prev_Low_Price = l,
                  Prev_Close_Price = c,
                  PerChange_Since_Prev =
                    todaysChangePerc,
                  ValChange_Sine_Prev = todaysChange,
                  d3 = v,
                  d4 = vw)
      options <- options %>% unnest('min')
      options <- as_tibble(options[-c(4, 9:18, 23:24)])
      names <- read.csv("company_names.csv")
      names <- rename(names, ticker = Symbol,
                             name = Name)
      names <- as_tibble(names[-c(3:5)])
      options <- merge(options, names, by = 'ticker')
      options <- options[c(1, 12, 2:11)]
  
    if (company != "all"){
    
    if (toupper(company) %in% options$ticker){
      options <- options %>%
        filter(ticker == toupper(company))
    }
    
    else if (toupper(company) %in% options$Name){
      output <- options %>%
        filter(Name == toupper(company))
    }
    # Otherwise, throw an informative error.
    else {
      message <- paste('ERROR: Argument for company was
                       not found in the ticker or the
                       name column. Returning all
                       companies.')
                       
    }
  }
  # Do nothing if the company value equals "all".
  else {
    
  output <- as.data.frame(options)
  # Return the output data.frame.
  return(output)
  }
}
c <- company()
```

```{r}
#Function for exchange
exchange <- function(exchange = "all"){
  url <- "https://api.polygon.io/v3/reference/tickers?active=true&limit=1000"
  query_list <- list(apiKey =
                       Sys.getenv("API_KEY"))
  my_data <- GET(url, query = query_list)
  parsed <- fromJSON(rawToChar(my_data$content))
  options <- as.data.frame(parsed$results)
  options$name <- toupper(options$name)
  options$market <- toupper(options$market)
  options <- options[-c(4, 7:12)]
  
    if (exchange != "all"){
    
    if (toupper(exchange) %in% options$primary_exchange){
      options <- options %>%
        filter(primary_exchange == toupper(exchange))
    }
    
    # Otherwise, throw an informative error.
    else {
      message <- paste('ERROR: Argument for exchange was
                       not found in the exchange column.
                       Returning all
                       exchanges')
                       
    }
  }
  # Do nothing if the company value equals "all".
  else {
    
  output <- as.data.frame(options)
  # Return the output data.frame.
  return(output)
  }
}
e <- exchange('xnys')
```

```{r}
#Function for type
type <- function(type = "all"){
  url <- "https://api.polygon.io/v3/reference/tickers?active=true&limit=1000"
  query_list <- list(apiKey =
                       Sys.getenv("API_KEY"))
  my_data <- GET(url, query = query_list)
  parsed <- fromJSON(rawToChar(my_data$content))
  options <- as.data.frame(parsed$results)
  options$name <- toupper(options$name)
  options$market <- toupper(options$market)
  options <- options[-c(4, 7:12)]
  
     if (type != "all"){
    
    if (toupper(type) %in% options$type){
      options <- options %>%
        filter(type == toupper(type))
    }
    
    # Otherwise, throw an informative error.
    else {
      message <- paste('ERROR: Argument for company was
                       not found in the type column. Returning
                       all types.')
                       
    }
  }
  # Do nothing if the company value equals "all".
  else {
    
  output <- as.data.frame(options)
  # Return the output data.frame.
  return(output)
  }
}
e <- type('UNIT')
```

```{r}
#Function for type
company <- function(company = "all") {
  url <- "https://api.polygon.io/v3/reference/tickers"
  
  query_list <- list(active = "true", limit = 1000, apiKey =
                       Sys.getenv("API_KEY"))
  
  if (company != "all") {
    query_list$q <- query
  }
  
  my_data <- GET(url, query = query_list)
  
  if (http_status(my_data)$category == "Success") {
    parsed <- fromJSON(rawToChar(my_data$content))
    results <- as.data.frame(parsed$results)
    
    if (nrow(results) > 0) {
      results <-as.data.frame(sapply(results, toupper))
      results <- results[-c(7, 9:12)]
      results <- results %>%
        filter(ticker == toupper(query) | 
                 name == toupper(query))
    }
    return(as_tibble(results))
    
  } 
  else {
    stop("Error retrieving data from the API.")
  }
}

company_trial_name <- company("AGILENT TECHNOLOGIES INC.")
company_trial_name 
company_trial_ticker <- company("AAPL")
company_trial_ticker
```


```{r}
bankAPI <- function(func,...){
  if (func == "company"){
    output <- company(...)
  }
  else if (func == "exchange"){
    output <- exchange(...)
  }
  else if (func == "type"){
    output <- type(...)
  }
  
  else {
    stop("ERROR: Argument for func is not valid!")
  }
  
  # Return the output from the appropriate function.
  return(output)
}
k <- bankAPI('type')
```

